[package]
name = "a1ctf"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.6"
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"
serde_json = "1.0.139"
serde = "1.0.218"
