name: Build

on:
  push:
    branches: ["dev"]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Get short commit SHA
        id: commit_sha
        run: echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/a1ctf
            ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/a1ctf
          tags: |
            latest
            dev-${{ steps.commit_sha.outputs.commit_sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

  prune:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    permissions:
      contents: read
      packages: write
    steps:
      - name: Prune old packages
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: a1ctf/a1ctf
          exclude-tags: latest
          keep-n-tagged: 5
          dry-run: false
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true
